# Generated by Django 3.1.7 on 2021-04-04 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listitapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['product_status', 'product_name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(db_index=True, max_length=25, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='In cart'),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='products',
            name='total_price',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listitapp.category', verbose_name='Category'),
        ),
    ]
