# Generated by Django 3.1.7 on 2021-05-12 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Category')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=25, verbose_name='Product')),
                ('price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Price')),
                ('quantity', models.FloatField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('total_price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total')),
                ('product_status', models.BooleanField(blank=True, null=True, verbose_name='In cart')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listitapp.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['product_status', 'product_name'],
            },
        ),
    ]
