# Generated by Django 3.1.7 on 2021-05-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listitapp', '0002_auto_20210512_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name', 'is_published'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(db_index=True, default='new product', max_length=25, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='In cart'),
        ),
    ]
