# Generated by Django 3.1.7 on 2021-06-22 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listitapp', '0005_users_list_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_list',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listitapp.category', verbose_name='Category'),
        ),
    ]
