# Generated by Django 3.1.7 on 2021-06-22 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listitapp', '0006_users_list_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users_list',
            options={'ordering': ['list_name'], 'verbose_name': "User's list", 'verbose_name_plural': "User's lists"},
        ),
    ]
