# Generated by Django 3.1.7 on 2021-06-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listitapp', '0009_auto_20210622_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='users_list',
        ),
        migrations.AddField(
            model_name='category',
            name='users_list',
            field=models.ManyToManyField(related_name='cats', to='listitapp.Users_List'),
        ),
    ]
