# Generated by Django 3.1.7 on 2021-06-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listitapp', '0010_auto_20210622_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='users_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='cats', to='listitapp.Users_List'),
        ),
    ]
