# Generated by Django 3.2.7 on 2021-10-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listitapp', '0011_auto_20210623_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_list',
            name='category_in_list',
            field=models.BooleanField(default=False, verbose_name='In list'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='users_list',
            field=models.ManyToManyField(blank=True, related_name='cats', to='listitapp.Users_List'),
        ),
    ]
