# Generated by Django 3.2.7 on 2021-10-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listitapp', '0012_auto_20211013_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_list',
            name='category_in_list',
        ),
    ]
