# Generated by Django 3.2.7 on 2021-10-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listitapp', '0013_remove_users_list_category_in_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='users_list',
        ),
        migrations.DeleteModel(
            name='Users_List',
        ),
    ]
