# Generated by Django 3.2.7 on 2021-10-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listitapp', '0015_alter_category_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Show'),
        ),
    ]
